[[tool.mypy.overrides]]
module = [
    # https://github.com/MagicStack/asyncpg/pull/577
    "asyncpg",
    "bs4",
    "PIL",
    "ruamel",
]
ignore_missing_imports = true

[tool.isort]
profile = "black"
force_to_top = "typing"
from_first = true
combine_as_imports = true
known_first_party = "mautrix"
line_length = 99

[tool.black]
line-length = 99
target-version = ["py38"]
